# See https://docs.coderabbit.ai/for details

language: "en-US"

reviews:
    profile: "chill"
    request_changes_workflow: false
    high_level_summary: true
    poem: true
    review_status: true
    review_details: false
    auto_review:
      enabled: true
      drafts: false
    path_filters:
      - "!node_modules/**"
      - "!.next/**"
      - "!src/app/(payload)/admin/importMap.js"
      - "!payload-types.ts"

chat:
  enabled: true
  auto_reply: true


  