/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | "Pacific/Midway"
  | "Pacific/Niue"
  | "Pacific/Honolulu"
  | "Pacific/Rarotonga"
  | "America/Anchorage"
  | "Pacific/Gambier"
  | "America/Los_Angeles"
  | "America/Tijuana"
  | "America/Denver"
  | "America/Phoenix"
  | "America/Chicago"
  | "America/Guatemala"
  | "America/New_York"
  | "America/Bogota"
  | "America/Caracas"
  | "America/Santiago"
  | "America/Buenos_Aires"
  | "America/Sao_Paulo"
  | "Atlantic/South_Georgia"
  | "Atlantic/Azores"
  | "Atlantic/Cape_Verde"
  | "Europe/London"
  | "Europe/Berlin"
  | "Africa/Lagos"
  | "Europe/Athens"
  | "Africa/Cairo"
  | "Europe/Moscow"
  | "Asia/Riyadh"
  | "Asia/Dubai"
  | "Asia/Baku"
  | "Asia/Karachi"
  | "Asia/Tashkent"
  | "Asia/Calcutta"
  | "Asia/Dhaka"
  | "Asia/Almaty"
  | "Asia/Jakarta"
  | "Asia/Bangkok"
  | "Asia/Shanghai"
  | "Asia/Singapore"
  | "Asia/Tokyo"
  | "Asia/Seoul"
  | "Australia/Brisbane"
  | "Australia/Sydney"
  | "Pacific/Guam"
  | "Pacific/Noumea"
  | "Pacific/Auckland"
  | "Pacific/Fiji";

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    "cloudinary-cleanup-jobs": CloudinaryCleanupJob;
    contact_form_responses: ContactFormResponse;
    "payload-kv": PayloadKv;
    "payload-locked-documents": PayloadLockedDocument;
    "payload-preferences": PayloadPreference;
    "payload-migrations": PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    "cloudinary-cleanup-jobs":
      CloudinaryCleanupJobsSelect<false> | CloudinaryCleanupJobsSelect<true>;
    contact_form_responses: ContactFormResponsesSelect<false> | ContactFormResponsesSelect<true>;
    "payload-kv": PayloadKvSelect<false> | PayloadKvSelect<true>;
    "payload-locked-documents":
      PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    "payload-preferences": PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    "payload-migrations": PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    app_homepage: AppHomepage;
    app_contactpage: AppContactpage;
    app_privacy: AppPrivacy;
    app_terms: AppTerm;
    app_navigation: AppNavigation;
    app_footer: AppFooter;
    app_cta: AppCta;
  };
  globalsSelect: {
    app_homepage: AppHomepageSelect<false> | AppHomepageSelect<true>;
    app_contactpage: AppContactpageSelect<false> | AppContactpageSelect<true>;
    app_privacy: AppPrivacySelect<false> | AppPrivacySelect<true>;
    app_terms: AppTermsSelect<false> | AppTermsSelect<true>;
    app_navigation: AppNavigationSelect<false> | AppNavigationSelect<true>;
    app_footer: AppFooterSelect<false> | AppFooterSelect<true>;
    app_cta: AppCtaSelect<false> | AppCtaSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: "users";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Important for accessibility and SEO
   */
  alt: string;
  caption?: string | null;
  type?: ("image" | "video" | "audio" | "document" | "dataset" | "other") | null;
  cloudinaryPublicId?: string | null;
  cloudinaryResourceType?: string | null;
  cloudinaryFormat?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cloudinary-cleanup-jobs".
 */
export interface CloudinaryCleanupJob {
  id: string;
  publicId: string;
  resourceType: string;
  filename: string;
  errorDetails?: string | null;
  status?: ("pending" | "failed" | "completed") | null;
  attempts?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Responses from the contact form. Read-only for admins.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_form_responses".
 */
export interface ContactFormResponse {
  id: string;
  /**
   * Submitter's email address
   */
  email: string;
  /**
   * Raw form field values as a JSON object
   */
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  submittedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: "users";
        value: string | User;
      } | null)
    | ({
        relationTo: "media";
        value: string | Media;
      } | null)
    | ({
        relationTo: "cloudinary-cleanup-jobs";
        value: string | CloudinaryCleanupJob;
      } | null)
    | ({
        relationTo: "contact_form_responses";
        value: string | ContactFormResponse;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: "users";
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: "users";
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  type?: T;
  cloudinaryPublicId?: T;
  cloudinaryResourceType?: T;
  cloudinaryFormat?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cloudinary-cleanup-jobs_select".
 */
export interface CloudinaryCleanupJobsSelect<T extends boolean = true> {
  publicId?: T;
  resourceType?: T;
  filename?: T;
  errorDetails?: T;
  status?: T;
  attempts?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_form_responses_select".
 */
export interface ContactFormResponsesSelect<T extends boolean = true> {
  email?: T;
  data?: T;
  submittedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app_homepage".
 */
export interface AppHomepage {
  id: string;
  hero: {
    badge: {
      text: string;
    };
    title: {
      main: string;
      highlight: string;
    };
    description: string;
    buttons?:
      | {
          label: string;
          href?: string | null;
          className?: string | null;
          icon?: string | null;
          id?: string | null;
        }[]
      | null;
    image?: {
      /**
       * Select or upload an image from Payload Media Library
       */
      media?: (string | null) | Media;
      /**
       * External image URL (used if no Media asset is attached)
       */
      src?: string | null;
      /**
       * Accessibility alt text
       */
      alt?: string | null;
    };
  };
  aboutUs: {
    badge: string;
    title: string;
    description: string;
    sections?:
      | {
          icon: string;
          title: string;
          description: string;
          stat: string;
          highlighted?: boolean | null;
          href?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  missionVision: {
    mission: {
      title: string;
      description: string;
      stat: {
        value: string;
        label: string;
      };
    };
    vision: {
      title: string;
      description: string;
    };
    images: {
      primary: {
        /**
         * Select or upload an image from Payload Media Library
         */
        media?: (string | null) | Media;
        /**
         * External image URL (used if no Media asset is attached)
         */
        src?: string | null;
        /**
         * Accessibility alt text
         */
        alt?: string | null;
      };
      secondary: {
        /**
         * Select or upload an image from Payload Media Library
         */
        media?: (string | null) | Media;
        /**
         * External image URL (used if no Media asset is attached)
         */
        src?: string | null;
        /**
         * Accessibility alt text
         */
        alt?: string | null;
      };
      additionalImages?:
        | {
            image?: {
              /**
               * Select or upload an image from Payload Media Library
               */
              media?: (string | null) | Media;
              /**
               * External image URL (used if no Media asset is attached)
               */
              src?: string | null;
              /**
               * Accessibility alt text
               */
              alt?: string | null;
            };
            id?: string | null;
          }[]
        | null;
    };
  };
  ourPartners: {
    title: string;
    description: string;
    partners?:
      | {
          logo?: {
            /**
             * Select or upload an image from Payload Media Library
             */
            media?: (string | null) | Media;
            /**
             * External image URL (used if no Media asset is attached)
             */
            src?: string | null;
            /**
             * Accessibility alt text
             */
            alt?: string | null;
          };
          name?: string | null;
          url?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  ourWork: {
    title: string;
    subtitle: string;
    featuredProject: {
      category: string;
      title: string;
      description: string;
      images?:
        | {
            img?: {
              /**
               * Select or upload an image from Payload Media Library
               */
              media?: (string | null) | Media;
              /**
               * External image URL (used if no Media asset is attached)
               */
              src?: string | null;
              /**
               * Accessibility alt text
               */
              alt?: string | null;
            };
            id?: string | null;
          }[]
        | null;
    };
  };
  team: {
    title: string;
    members?:
      | {
          name: string;
          role: string;
          image?: {
            /**
             * Select or upload an image from Payload Media Library
             */
            media?: (string | null) | Media;
            /**
             * External image URL (used if no Media asset is attached)
             */
            src?: string | null;
            /**
             * Accessibility alt text
             */
            alt?: string | null;
          };
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app_contactpage".
 */
export interface AppContactpage {
  id: string;
  hero: {
    badge: {
      text: string;
    };
    title: {
      main: string;
      highlight: string;
    };
    description: string;
    buttons?:
      | {
          label: string;
          href?: string | null;
          className?: string | null;
          icon?: string | null;
          id?: string | null;
        }[]
      | null;
    image?: {
      /**
       * Select or upload an image from Payload Media Library
       */
      media?: (string | null) | Media;
      /**
       * External image URL (used if no Media asset is attached)
       */
      src?: string | null;
      /**
       * Accessibility alt text
       */
      alt?: string | null;
    };
  };
  contactInfo: {
    title: string;
    office: {
      title: string;
      address: string;
    };
    phone: {
      title: string;
      numbers?:
        | {
            countryCode: string;
            number: string;
            id?: string | null;
          }[]
        | null;
    };
    email: {
      title: string;
      addresses?:
        | {
            address: string;
            id?: string | null;
          }[]
        | null;
    };
  };
  contactForm: {
    title: string;
    formFields?:
      | {
          fieldName: string;
          fieldLabel: string;
          fieldType:
            "text" | "email" | "tel" | "textarea" | "select" | "checkbox" | "radio" | "file";
          selectOptions?:
            | {
                label: string;
                value: string;
                id?: string | null;
              }[]
            | null;
          isChecked?: boolean | null;
          radioOptions?:
            | {
                label: string;
                value: string;
                id?: string | null;
              }[]
            | null;
          fileTypes?:
            | {
                type: "pdf" | "image" | "document" | "video" | "audio" | "other";
                id?: string | null;
              }[]
            | null;
          fieldPlaceholder: string;
          width?: ("full" | "half") | null;
          regexValidation?: string | null;
          className?: string | null;
          fieldRequired?: boolean | null;
          id?: string | null;
        }[]
      | null;
    submitButtonText: string;
  };
  map: {
    title: string;
    locationText?: string | null;
    embedUrl?: string | null;
    mapImage?: {
      /**
       * Select or upload an image from Payload Media Library
       */
      media?: (string | null) | Media;
      /**
       * External image URL (used if no Media asset is attached)
       */
      src?: string | null;
      /**
       * Accessibility alt text
       */
      alt?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app_privacy".
 */
export interface AppPrivacy {
  id: string;
  title: string;
  description: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  contactCta: {
    title: string;
    description: string;
    button: {
      label: string;
      href: string;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app_terms".
 */
export interface AppTerm {
  id: string;
  title: string;
  description: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  contactCta: {
    title: string;
    description: string;
    button: {
      label: string;
      href: string;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app_navigation".
 */
export interface AppNavigation {
  id: string;
  logo?: {
    /**
     * Select or upload an image from Payload Media Library
     */
    media?: (string | null) | Media;
    /**
     * External image URL (used if no Media asset is attached)
     */
    src?: string | null;
    /**
     * Accessibility alt text
     */
    alt?: string | null;
  };
  brandName: {
    text: string;
  };
  navItems?:
    | {
        label: string;
        href: string;
        isDropdown?: boolean | null;
        groupA?: {
          title?: string | null;
          items?:
            | {
                label: string;
                href: string;
                id?: string | null;
              }[]
            | null;
        };
        groupB?: {
          title?: string | null;
          items?:
            | {
                label: string;
                href: string;
                id?: string | null;
              }[]
            | null;
        };
        id?: string | null;
      }[]
    | null;
  ctaButton: {
    label: string;
    href?: string | null;
    className?: string | null;
    icon?: string | null;
    id?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app_footer".
 */
export interface AppFooter {
  id: string;
  brand: {
    name: string;
    icon: string;
    address: string;
    /**
     * Direct Maps link for the location (optional)
     */
    googleMapsUrl?: string | null;
    phone: string;
    email: string;
  };
  linkGroups?:
    | {
        title: string;
        links?:
          | {
              label: string;
              href: string;
              isActive?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  copyrightYear?: string | null;
  copyright: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app_cta".
 */
export interface AppCta {
  id: string;
  cta: {
    title: string;
    highlight: string;
    buttons?:
      | {
          label: string;
          href?: string | null;
          className?: string | null;
          icon?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app_homepage_select".
 */
export interface AppHomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?:
          | T
          | {
              text?: T;
            };
        title?:
          | T
          | {
              main?: T;
              highlight?: T;
            };
        description?: T;
        buttons?:
          | T
          | {
              label?: T;
              href?: T;
              className?: T;
              icon?: T;
              id?: T;
            };
        image?:
          | T
          | {
              media?: T;
              src?: T;
              alt?: T;
            };
      };
  aboutUs?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
        sections?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              stat?: T;
              highlighted?: T;
              href?: T;
              id?: T;
            };
      };
  missionVision?:
    | T
    | {
        mission?:
          | T
          | {
              title?: T;
              description?: T;
              stat?:
                | T
                | {
                    value?: T;
                    label?: T;
                  };
            };
        vision?:
          | T
          | {
              title?: T;
              description?: T;
            };
        images?:
          | T
          | {
              primary?:
                | T
                | {
                    media?: T;
                    src?: T;
                    alt?: T;
                  };
              secondary?:
                | T
                | {
                    media?: T;
                    src?: T;
                    alt?: T;
                  };
              additionalImages?:
                | T
                | {
                    image?:
                      | T
                      | {
                          media?: T;
                          src?: T;
                          alt?: T;
                        };
                    id?: T;
                  };
            };
      };
  ourPartners?:
    | T
    | {
        title?: T;
        description?: T;
        partners?:
          | T
          | {
              logo?:
                | T
                | {
                    media?: T;
                    src?: T;
                    alt?: T;
                  };
              name?: T;
              url?: T;
              id?: T;
            };
      };
  ourWork?:
    | T
    | {
        title?: T;
        subtitle?: T;
        featuredProject?:
          | T
          | {
              category?: T;
              title?: T;
              description?: T;
              images?:
                | T
                | {
                    img?:
                      | T
                      | {
                          media?: T;
                          src?: T;
                          alt?: T;
                        };
                    id?: T;
                  };
            };
      };
  team?:
    | T
    | {
        title?: T;
        members?:
          | T
          | {
              name?: T;
              role?: T;
              image?:
                | T
                | {
                    media?: T;
                    src?: T;
                    alt?: T;
                  };
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app_contactpage_select".
 */
export interface AppContactpageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?:
          | T
          | {
              text?: T;
            };
        title?:
          | T
          | {
              main?: T;
              highlight?: T;
            };
        description?: T;
        buttons?:
          | T
          | {
              label?: T;
              href?: T;
              className?: T;
              icon?: T;
              id?: T;
            };
        image?:
          | T
          | {
              media?: T;
              src?: T;
              alt?: T;
            };
      };
  contactInfo?:
    | T
    | {
        title?: T;
        office?:
          | T
          | {
              title?: T;
              address?: T;
            };
        phone?:
          | T
          | {
              title?: T;
              numbers?:
                | T
                | {
                    countryCode?: T;
                    number?: T;
                    id?: T;
                  };
            };
        email?:
          | T
          | {
              title?: T;
              addresses?:
                | T
                | {
                    address?: T;
                    id?: T;
                  };
            };
      };
  contactForm?:
    | T
    | {
        title?: T;
        formFields?:
          | T
          | {
              fieldName?: T;
              fieldLabel?: T;
              fieldType?: T;
              selectOptions?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              isChecked?: T;
              radioOptions?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              fileTypes?:
                | T
                | {
                    type?: T;
                    id?: T;
                  };
              fieldPlaceholder?: T;
              width?: T;
              regexValidation?: T;
              className?: T;
              fieldRequired?: T;
              id?: T;
            };
        submitButtonText?: T;
      };
  map?:
    | T
    | {
        title?: T;
        locationText?: T;
        embedUrl?: T;
        mapImage?:
          | T
          | {
              media?: T;
              src?: T;
              alt?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app_privacy_select".
 */
export interface AppPrivacySelect<T extends boolean = true> {
  title?: T;
  description?: T;
  content?: T;
  contactCta?:
    | T
    | {
        title?: T;
        description?: T;
        button?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app_terms_select".
 */
export interface AppTermsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  content?: T;
  contactCta?:
    | T
    | {
        title?: T;
        description?: T;
        button?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app_navigation_select".
 */
export interface AppNavigationSelect<T extends boolean = true> {
  logo?:
    | T
    | {
        media?: T;
        src?: T;
        alt?: T;
      };
  brandName?:
    | T
    | {
        text?: T;
      };
  navItems?:
    | T
    | {
        label?: T;
        href?: T;
        isDropdown?: T;
        groupA?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
            };
        groupB?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
            };
        id?: T;
      };
  ctaButton?:
    | T
    | {
        label?: T;
        href?: T;
        className?: T;
        icon?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app_footer_select".
 */
export interface AppFooterSelect<T extends boolean = true> {
  brand?:
    | T
    | {
        name?: T;
        icon?: T;
        address?: T;
        googleMapsUrl?: T;
        phone?: T;
        email?: T;
      };
  linkGroups?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              isActive?: T;
              id?: T;
            };
        id?: T;
      };
  copyrightYear?: T;
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app_cta_select".
 */
export interface AppCtaSelect<T extends boolean = true> {
  cta?:
    | T
    | {
        title?: T;
        highlight?: T;
        buttons?:
          | T
          | {
              label?: T;
              href?: T;
              className?: T;
              icon?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: "full";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module "payload" {
  export interface GeneratedTypes extends Config {}
}
